/*

 LOGO_BACKGROUND_5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\moon\Documents\GitHub\KanaPop\res\logo_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LogoBackground5Width 20
#define LogoBackground5Height 18
#define LogoBackground5Bank 0

extern unsigned char LogoBackground5[];

/* End of LOGO_BACKGROUND_5.H */
