/*

 LOGO_BACKGROUND_3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\moon\Documents\GitHub\KanaPop\res\logo_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LogoBackground3Width 20
#define LogoBackground3Height 18
#define LogoBackground3Bank 0

extern unsigned char LogoBackground3[];

/* End of LOGO_BACKGROUND_3.H */
